{
 "title": "dolphindb",
 "time": { "from": "now-1m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_name",
    "query": {
     "query": "label_values(dolphindb_metric_avg_load, dolphindb_io_dolphindb_name)"
    }
   },
   {
    "name": "dolphindb_node",
    "query": {
     "query": "label_values(dolphindb_metric_avg_load{dolphindb_io_dolphindb_name=~\"$cluster_name\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "KPI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Jobs",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dolphindb_metric_running_jobs{pod=~\"$dolphindb_node\", dolphindb_io_dolphindb_name=~\"$cluster_name\"}",
     "legendFormat": "{{pod}} "
    }
   ]
  },
  {
   "title": "Average Load",
   "type": "timeseries",
   "description": "average load",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "dolphindb_metric_avg_load{pod=~\"$dolphindb_node\", dolphindb_io_dolphindb_name=~\"$cluster_name\"}",
     "legendFormat": "{{pod}}"
    },
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dolphindb_metric_cpu_usage{pod=~\"$dolphindb_node\", dolphindb_io_dolphindb_name=~\"$cluster_name\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - dolphindb_metric_disk_free_space_ratio{ pod=~\"$dolphindb_node\", dolphindb_io_dolphindb_name=~\"$cluster_name\", dolphindb_io_component_type=\"Datanode\"}) * 100",
     "legendFormat": "{{pod}} "
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "dolphindb_metric_memory_used{pod=~\"$dolphindb_node\", dolphindb_io_dolphindb_name=~\"$cluster_name\"}/(1024*1024)",
     "legendFormat": "{{pod}} Used"
    }
   ]
  },
  {
   "title": "Memory allocated",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "dolphindb_metric_memory_alloc{pod=~\"$dolphindb_node\", dolphindb_io_dolphindb_name=~\"$cluster_name\"}/(1024 * 1024)",
     "legendFormat": "{{pod}} "
    }
   ]
  },
  {
   "title": "Disk read rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "dolphindb_metric_disk_read_rate{pod=~\"$dolphindb_node\", dolphindb_io_dolphindb_name=~\"$cluster_name\"}/(1024 * 1024)",
     "legendFormat": "{{pod}} "
    }
   ]
  },
  {
   "title": "Disk write rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "dolphindb_metric_disk_write_rate{pod=~\"$dolphindb_node\", dolphindb_io_dolphindb_name=~\"$cluster_name\"}/(1024 * 1024)",
     "legendFormat": "{{pod}} "
    }
   ]
  },
  {
   "title": "Network receive rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "dolphindb_metric_network_recv_rate{pod=~\"$dolphindb_node\", dolphindb_io_dolphindb_name=~\"$cluster_name\"} / (1024 * 1024)",
     "legendFormat": "{{pod}} "
    }
   ]
  },
  {
   "title": "Network send rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Mibits" } },
   "targets": [
    {
     "expr": "dolphindb_metric_network_send_rate{pod=~\"$dolphindb_node\", dolphindb_io_dolphindb_name=~\"$cluster_name\"} / (1024 * 1024)",
     "legendFormat": "{{pod}} "
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk free space",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "targets": [
      {
       "expr": "dolphindb_metric_disk_free_space{pod=~\"$dolphindb_node\", dolphindb_io_dolphindb_name=~\"$cluster_name\"}/ (1024 * 1024 * 1024)",
       "legendFormat": "{{pod}} "
      }
     ]
    },
    {
     "title": "Disk Capacity",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "targets": [
      {
       "expr": "dolphindb_metric_disk_capacity{pod=~\"$dolphindb_node\", dolphindb_io_dolphindb_name=~\"$cluster_name\"}/ (1024 * 1024 *1024)",
       "legendFormat": "{{pod}} "
      }
     ]
    },
    {
     "title": "Last minute read volume",
     "type": "timeseries",
     "description": "the size of disk reading last  minute",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "dolphindb_metric_last_minute_read_volume{pod=~\"$dolphindb_node\", dolphindb_io_dolphindb_name=~\"$cluster_name\"}/ (1024 * 1024)",
       "legendFormat": "{{pod}} "
      }
     ]
    },
    {
     "title": "Last minute write volume",
     "type": "timeseries",
     "description": "the size of disk writing last  minute",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "dolphindb_metric_last_minute_write_volume{pod=~\"$dolphindb_node\", dolphindb_io_dolphindb_name=~\"$cluster_name\"}/ (1024 * 1024)",
       "legendFormat": "{{pod}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Job",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queued Jobs",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "dolphindb_metric_queued_jobs{pod=~\"$dolphindb_node\", dolphindb_io_dolphindb_name=~\"$cluster_name\"}",
       "legendFormat": "{{pod}} "
      }
     ]
    },
    {
     "title": "Job Load",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "dolphindb_metric_job_load{pod=~\"$dolphindb_node\", dolphindb_io_dolphindb_name=~\"$cluster_name\"}",
       "legendFormat": "{{pod}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Query",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max last100 query time",
     "type": "timeseries",
     "description": "max execution time of the previous 100 finished queries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "dolphindb_metric_max_last100_query_time{pod=~\"$dolphindb_node\", dolphindb_io_dolphindb_name=~\"$cluster_name\"} / (1000*1000)",
       "legendFormat": "{{pod}} "
      }
     ]
    },
    {
     "title": "Max last10 query time",
     "type": "timeseries",
     "description": "max execution time of the previous 10 finished queries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "dolphindb_metric_max_last10_query_time{pod=~\"$dolphindb_node\", dolphindb_io_dolphindb_name=~\"$cluster_name\"} / (1000 * 1000)",
       "legendFormat": "{{pod}} "
      }
     ]
    },
    {
     "title": "Med last100 query time",
     "type": "timeseries",
     "description": "median execution time of the previous 100 finished queries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "dolphindb_metric_med_last100_query_time{pod=~\"$dolphindb_node\", dolphindb_io_dolphindb_name=~\"$cluster_name\"} / (1000 * 1000)",
       "legendFormat": "{{pod}} "
      }
     ]
    },
    {
     "title": "Med last10 query time",
     "type": "timeseries",
     "description": "median execution time of the previous 10 finished queries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "dolphindb_metric_med_last10_query_time{pod=~\"$dolphindb_node\", dolphindb_io_dolphindb_name=~\"$cluster_name\"} / (1000 * 1000)",
       "legendFormat": "{{pod}} "
      }
     ]
    },
    {
     "title": "Max running query time",
     "type": "timeseries",
     "description": "the maximum elapsed time of currently running query",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "dolphindb_metric_max_running_query_time{pod=~\"$dolphindb_node\", dolphindb_io_dolphindb_name=~\"$cluster_name\"}",
       "legendFormat": "{{pod}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last message latency",
     "type": "timeseries",
     "description": "the latency of  the last reciving message",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "dolphindb_metric_last_msg_latency{pod=~\"$dolphindb_node\", dolphindb_io_dolphindb_name=~\"$cluster_name\"} / (1000 * 1000)>= 0",
       "legendFormat": "{{pod}} "
      }
     ]
    },
    {
     "title": "Cum message latency",
     "type": "timeseries",
     "description": "the weighted average latency of all received messages during  the subscription",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "dolphindb_metric_cum_msg_latency{pod=~\"$dolphindb_node\", dolphindb_io_dolphindb_name=~\"$cluster_name\"} / (1000 * 1000)>= 0",
       "legendFormat": "{{dolphindb_io_controller_name}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last minute network received",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "dolphindb_metric_last_minute_network_recv{pod=~\"$dolphindb_node\", dolphindb_io_dolphindb_name=~\"$cluster_name\"}/(1024*1024)",
       "legendFormat": "{{statefulset_kubernetes_io_pod_name}} "
      }
     ]
    },
    {
     "title": "Last minute network sent",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "dolphindb_metric_last_minute_network_send{pod=~\"$dolphindb_node\", dolphindb_io_dolphindb_name=~\"$cluster_name\"} / (1024 * 1024)",
       "legendFormat": "{{pod}} "
      }
     ]
    }
   ]
  }
 ]
}