apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "grafana.fullname" . }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
data:
  grafana.ini: |
{{- range $key, $value := index .Values "grafana.ini" }}
    [{{ $key }}]
    {{- range $elem, $elemVal := $value }}
    {{- if kindIs "invalid" $elemVal }}
    {{ $elem }} =
    {{- else if kindIs "string" $elemVal }}
    {{ $elem }} = {{ tpl $elemVal $ }}
    {{- else }}
    {{ $elem }} = {{ $elemVal }}
    {{- end }}
    {{- end }}
{{- end }}
  datasources.yaml: |
{{- include "grafana.server.datasources" . | nindent 4 }}
  dashboards.yaml: |
    apiVersion: 1
    providers:
    - name: 'dolphindb'
      orgId: 1
      folder: ''
      type: file
      editable: true
      updateIntervalSeconds: 10
      allowUiUpdates: false
      options:
        path: /var/lib/grafana/dashboards
