apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dolphindbs.dolphindb.dolphindb.io
spec:
  group: dolphindb.dolphindb.io
  names:
    kind: DolphinDB
    listKind: DolphinDBList
    plural: dolphindbs
    singular: dolphindb
    shortNames:
      - ddb
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          x-kubernetes-preserve-unknown-fields: true
          type: object
      served: true
      storage: true
      subresources:
        # enables the status subresource
        status: { }
      additionalPrinterColumns:
        - name: Mode
          type: string
          jsonPath: .spec.mode
        - name: Status
          type: string
          jsonPath: .status.phase
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
