apiVersion: v1
kind: Service
metadata:
  name: {{ template "grafana.fullname" . }}
  labels:
    dolphindb.io/component: "grafana"
    {{- include "grafana.labels" . | nindent 4 }}
spec:
{{- if (or (eq .Values.service.type "ClusterIP") (and (empty .Values.service.type) (empty .Values.global.serviceType))) }}
  type: ClusterIP
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{end}}
{{- else if eq .Values.service.type "LoadBalancer" }}
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
  {{- end -}}
{{- else if eq .Values.service.type "NodePort"}}
  type: {{ .Values.service.type }}
{{- else }}
  type: {{ .Values.global.serviceType }}
{{- end }}
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
{{ if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{.Values.service.nodePort}}
{{ end }}
  {{- if .Values.extraExposePorts }}
  {{- tpl (toYaml .Values.extraExposePorts) . | indent 4 }}
  {{- end }}
  selector:
    {{- include "grafana.selectorLabels" . | nindent 4 }}
