apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dolphindbCloudPortal.fullName" . }}
  labels:
    app.kubernetes.io/name: {{ include "dolphindbCloudPortal.fullName" . }}
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
      worker_connections  1024;
    }

    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';
      access_log  /var/log/nginx/access.log  main;
      sendfile        on;
      keepalive_timeout  65;

      server {
        listen       8080;
        server_name  localhost;

        client_max_body_size 100m;
        client_body_buffer_size 10m;

        location / {
          if ($request_filename ~* .*\.(?:htm|html)$) {
            add_header Cache-Control "private, no-store, no-cache, must-revalidate, proxy-revalidate";
            access_log on;
          }
          root   /dolphindb-cloud/;
          index  index.html index.htm;
          try_files $uri $uri/ /index.html;
        }

        location /v1 {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header REMOTE-HOST $remote_addr;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection upgrade;
    
            proxy_pass http://dolphindb-webserver.{{ .Release.Namespace }}.{{ include "domain.suffix" . }}:8080/v1;
            proxy_redirect default;
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Headers X-Requested-With;
            add_header Access-Control-Allow-Methods GET,POST,OPTIONS;
            proxy_read_timeout 300s;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
          root   /usr/share/nginx/html;
        }
      }
    }
    