apiVersion: v1
kind: Service
metadata:
  name: {{ include  "dolphindbOperator.fullName" . }}
  labels:
    app: {{ include  "dolphindbOperator.fullName" . }}
spec:
  ports:
    - port: 9443
      targetPort: 9443
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "dolphindbOperator.fullName" . }}
