global:
  registry: ""
  repository: dolphindb
  storageClass: ""
  serviceType: NodePort
  serviceAccount: dolphindb-mgr-sa
  version: v1.1.0
  allNamespace: false
  localTimeFileHostPath: "/etc/localtime"
  customDomainSuffix: ""
  nodeAffinity:
#    requiredDuringSchedulingIgnoredDuringExecution:
#      nodeSelectorTerms:
#        - matchExpressions:
#            - key: dolphindb.io/pod
#              operator: In
#              values:
#                - dolphindb
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
            - key: dolphindb.io/pod
              operator: In
              values:
                - dolphindb
  existingLokiAddress: ""
  minPersistentVolumeSize: ""

dolphindb-operator:
  enabled: true
  replicaCount: 2
  imageTag: ""

dolphindb-webserver:
  enabled: true
  replicaCount: 2
  imageTag: ""
  nodePortIP: ""

dolphindb:
  serviceType: ""
  coreDumpDir: "/data/ddb/core"
  localTimeFileMountPath: "/etc/localtime"
  controllerDataSize: 200Mi
  datanodeDataSize: 200Mi
  disableExporter: false
  logCleanLimit: 0.9
  images:
    default:
      dolphindbConfigLoader: ""
      dolphindbServiceManager: ""
      dolphindbExporter: ""
      dolphindbCleaner: ""
      promtail: "2.4.1"

promtailConfig:
  name: dolphindb-promtail-config

license:
  name: dolphindb-license
  content: ""
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 1
      memory: 1Gi

grafana:
  enabled: true

prometheus:
  enabled: true

alertmanager:
  enabled: true
  persistence:
    enabled: false

node-exporter:
  enabled: true

loki:
  enabled: true
