apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    dolphindb.io/promtail.config: promtail
  name: dolphindb-promtail-config
data:
  promtail-config.yaml: |-
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
      grpc_server_max_send_msg_size: 21000000
      grpc_server_max_recv_msg_size: 21000000
      grpc_server_max_concurrent_streams: 0

    positions:
      filename: ${LogDir}/positions.yaml

    clients:
      - url: {{ include "loki.address" . }}/loki/api/v1/push

    scrape_configs:
    - job_name: standalone_log_scrape
      static_configs:
      - labels:
          job: standalone_log
          pod_name: ${PodName}
          pod_namespace: ${Namespace}
          __path__: ${LogDir}/*standalone*.log*
      pipeline_stages:
        - regex:
            expression: (?P<time>[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{6}) <(?P<level>DEBUG|INFO|ERROR|WARNING)> :(?P<content>.*)
        - labels:
            level:
        - timestamp:
            format: 2006-01-02 15:04:05.000000
            source: time
        - output:
            source: content

    - job_name: agent_log_scrape
      static_configs:
      - labels:
          job: agent_log
          pod_name: ${PodName}
          pod_namespace: ${Namespace}
          __path__: ${LogDir}/agent*.log*
      pipeline_stages:
        - regex:
            expression: (?P<time>[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{6}) <(?P<level>DEBUG|INFO|ERROR|WARNING)> :(?P<content>.*)
        - labels:
            level:
        - timestamp:
            format: 2006-01-02 15:04:05.000000
            source: time
        - output:
            source: content      
    
    - job_name: controller_log_scrape
      static_configs:
      - labels:
          job: controller_log
          pod_name: ${PodName}
          pod_namespace: ${Namespace}
          __path__: ${LogDir}/controller*.log*
      pipeline_stages:
        - regex:
            expression: (?P<time>[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{6}) <(?P<level>DEBUG|INFO|ERROR|WARNING)> :(?P<content>.*)
        - labels:
            level:
        - timestamp:
            format: 2006-01-02 15:04:05.000000
            source: time
        - output:
            source: content  

    - job_name: node_log_scrape
      static_configs:
      - labels:
          job: node_log
          pod_name: ${PodName}
          pod_namespace: ${Namespace}
          __path__: ${LogDir}/*node[0-9].log*
      pipeline_stages:
        - regex:
            expression: (?P<time>[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{6}) <(?P<level>DEBUG|INFO|ERROR|WARNING)> :(?P<content>.*)
        - labels:
            level:
        - timestamp:
            format: 2006-01-02 15:04:05.000000
            source: time
        - output:
            source: content

    - job_name: job_log_scrape
      static_configs:
      - labels:
          job: job_log
          pod_name: ${PodName}
          pod_namespace: ${Namespace}
          __path__: ${LogDir}/*node[0-9]_job.log*   

    - job_name: output_scrape
      static_configs:
      - labels:
          job: output
          pod_name: ${PodName}
          pod_namespace: ${Namespace}
          __path__: ${LogDir}/*.out*