apiVersion: rbac.authorization.k8s.io/v1
kind: {{ include "rbac.roleBinding.kind" . }}
metadata:
  name: {{ .Values.global.serviceAccount }}
  labels:
    app: {{ .Values.global.serviceAccount }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.global.serviceAccount }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: {{ include "rbac.role.kind" . }}
  name: {{ .Values.global.serviceAccount }}
  apiGroup: rbac.authorization.k8s.io