{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "alertmanager.labels" . | nindent 4 }}
  name: {{ include "alertmanager.fullname" . }}
spec:
  accessModes:
    {{ toYaml .Values.persistence.accessModes | indent 4 }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- else if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- if .Values.persistence.selector }}
  selector:
  {{- toYaml .Values.persistence.selector | nindent 4 }}
  {{- end -}}
{{- end -}}